/**
 * The acceptance criterion for versioned settlement, and nothing else.
 *
 *   > Given the same historical inputs, rules, participant order and engine
 *   > version, the versioned engine produces exactly the settlement the
 *   > original engine produced.
 *
 * Until that is proven, nothing may overwrite historical money.
 *
 * What makes this a proof rather than a restatement: the fixtures were
 * generated by `scripts/generateEngineFixtures.ts` from each version's
 * ORIGINAL source, checked out of git —
 *
 *     v1  a865e06^     v2  a865e06     v3  a8d7734
 *
 * — not from the code under test. A fixture generated from this engine would
 * only prove the engine agrees with itself. These files are what the code that
 * decided real money in August actually returned.
 *
 * Two layers per version:
 *
 *   digest   sha256 over all 22,400 canonical results in matrix order. Any
 *            change to any case in any position fails it.
 *   samples  every 400th case with its full expected output, so a failure
 *            says WHICH number moved rather than only THAT one did.
 *
 * If this suite goes red, the fix is a NEW ENGINE VERSION. It is never a
 * regenerated fixture. Regenerating is how a fixture stops being evidence, and
 * the generator refuses to overwrite an existing file for exactly that reason.
 */

import { describe, expect, it } from 'vitest';
import { computeSettlementAt, computeSettlement, EngineVersion, CURRENT_ENGINE_VERSION } from './settlementEngine.js';
import { canonicalise, digestOf, fixtureCases } from './engineFixtureMatrix.js';

import v1 from './fixtures/engine-v1.json' with { type: 'json' };
import v2 from './fixtures/engine-v2.json' with { type: 'json' };
import v3 from './fixtures/engine-v3.json' with { type: 'json' };

const FIXTURES: Record<EngineVersion, typeof v1> = { 1: v1, 2: v2, 3: v3 };

const cases = fixtureCases();

describe.each([1, 2, 3] as EngineVersion[])('engine v%i reproduces the version that shipped', (version) => {
  const fixture = FIXTURES[version];

  it('agrees with the recorded digest across every case', () => {
    expect(fixture.caseCount).toBe(cases.length);

    const canonical = cases.map((c) => canonicalise(computeSettlementAt(version, c.players, c.settings, c.opts)));
    expect(digestOf(canonical)).toBe(fixture.digest);
  });

  it('matches every recorded sample field for field', () => {
    let checked = 0;
    for (const sample of fixture.samples) {
      const c = cases[sample.index];
      const actual = JSON.parse(canonicalise(computeSettlementAt(version, c.players, c.settings, c.opts)));
      // Named so a failure reads as "v1 case 4800 (three, fee does not divide)".
      expect(actual, `v${version} case ${sample.index} (${sample.table})`).toEqual(sample.expected);
      checked += 1;
    }
    // A fixture that lost its samples would pass an empty loop silently.
    expect(checked).toBe(fixture.samples.length);
    expect(checked).toBeGreaterThan(50);
  });

  it('was generated from that version\'s own source, not from this engine', () => {
    expect(fixture.engineVersion).toBe(version);
    expect(fixture.generatedFrom).toMatch(/^[0-9a-f]{7}\^?:apps\/api\/src\/modules\/offlineSessions\/settlementEngine\.ts$/);
  });
});

describe('the current engine is unchanged by versioning it', () => {
  it('computeSettlement still produces exactly what production produced', () => {
    // The narrowest statement of the whole exercise: the default entry point,
    // untouched signature, still lands on the v3 fixture — which was recorded
    // from a8d7734, the commit running in production.
    const canonical = cases.map((c) => canonicalise(computeSettlement(c.players, c.settings, c.opts)));
    expect(digestOf(canonical)).toBe(v3.digest);
  });

  it('defaults to the current version, so live settlement never picks a version', () => {
    expect(CURRENT_ENGINE_VERSION).toBe(3);
    for (const c of cases.slice(0, 200)) {
      expect(computeSettlement(c.players, c.settings, c.opts)).toEqual(
        computeSettlementAt(CURRENT_ENGINE_VERSION, c.players, c.settings, c.opts)
      );
    }
  });
});

describe('the three versions are genuinely different', () => {
  it('no two versions share a digest', () => {
    // If a divergence were dropped, two versions would agree everywhere and
    // this is the cheapest way to notice.
    const digests = [v1.digest, v2.digest, v3.digest];
    expect(new Set(digests).size).toBe(3);
  });
});
